In [1]:
import numpy as np

In [13]:
# Reading training and testing data
train_data = np.loadtxt('Datasets/training_diabetes_x_y_train.csv',delimiter=",")
test_data = np.loadtxt('Datasets/test_diabetes_x_test.csv',delimiter=",")

In [5]:
train_data

array([[ -4.91050164e-02,  -4.46416365e-02,   1.60854917e-01, ...,
          2.80165065e-02,   1.13486232e-02,   3.46000000e+02],
       [ -7.09002471e-02,   5.06801187e-02,  -8.91974838e-02, ...,
         -1.29079423e-02,  -5.49250874e-02,   1.04000000e+02],
       [  1.75052192e-03,  -4.46416365e-02,  -7.08746786e-02, ...,
         -2.25121719e-02,   7.20651633e-03,   4.90000000e+01],
       ..., 
       [  2.35457526e-02,  -4.46416365e-02,   7.03187031e-02, ...,
         -1.91970476e-02,  -9.36191133e-03,   2.88000000e+02],
       [  1.62806757e-02,   5.06801187e-02,   7.24743273e-02, ...,
         -2.36445576e-02,   6.10539062e-02,   1.31000000e+02],
       [ -9.14709343e-03,   5.06801187e-02,  -3.09956318e-02, ...,
          6.20931562e-03,   2.79170509e-02,   4.20000000e+01]])

In [6]:
# shape of training data
train_data.shape

(331, 11)

In [11]:
# Input Parameters
x_train = train_data[:,0:10]
print(x_train.shape)

(331, 10)


In [12]:
# Output
y_train = train_data[:,10]
print(y_train.shape)

(331,)


In [14]:
# Creating Linear Regresion Objcet
from sklearn.linear_model import LinearRegression
algorithm1 = LinearRegression()

In [15]:
# Fiting the algorithm
algorithm1.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
# slope for eq y = mx + c
m = algorithm1.coef_ 
m

array([  21.73408096, -256.66866675,  569.60940087,  303.63233545,
       -833.11088526,  525.74313633,  136.07129167,  140.89458927,
        731.44498492,   53.32119133])

In [19]:
# Intercept for eq y = mx + c
c = algorithm1.intercept_
c

150.702574894566

In [20]:
# Predicting the output for test data
y_predicted = algorithm1.predict(test_data)

In [21]:
y_predicted

array([ 105.52974799,  105.8039198 ,  178.60857225,   79.3828781 ,
         52.95868706,   98.87263854,  150.71755448,   34.86515216,
        113.13535727,  161.50184038,  135.8615611 ,   94.71592222,
        138.48094422,  141.37441723,  158.76862662,  171.65288616,
        106.44835654,  103.92659639,   95.38693889,  167.40118092,
        166.53426278,  101.53464712,  252.45035972,  147.02258547,
        214.78906632,  161.27557106,  210.61315228,   71.78091585,
        189.65032431,  206.6134259 ,  219.98643455,  168.80192534,
        116.84846127,  178.74399639,   77.03247418,   59.54633214,
        111.5673781 ,  156.95186739,  154.59591259,  198.94457493,
        115.53884017,  153.46699024,   84.96179518,  113.70337192,
        142.14155617,  147.31040378,   82.78072358,   77.89237327,
        128.99006192,  261.58712282,  213.31187775,  243.98791257,
        167.68132094,  183.69712124,  166.85926884,  202.11440188,
        220.39235543,  172.40288024,  176.60897931,  109.04656

In [24]:
# writing the predicted output to a file. The value will be upto 5 decimal places
np.savetxt('Datasets/LinearRegressionOutput.csv', y_predicted, fmt='%5f')