In [3]:
# python list and arrays are a little slow. THey take a lot of space for storage
# They are not compact
# Numpy library is written in C
# All elements in numpy array have to be of the same type, important
import numpy as np
l = [2,1,4]
np.array(l)

array([2, 1, 4])

In [4]:
l = [1,2,"3"]
np.array(l)# here it converts every element into a string

array(['1', '2', '3'], 
      dtype='<U21')

In [11]:
l = [1,2,3]
a = np.zeros(10) # array with all zeroes
print(a)
print(a.dtype) # gives us all float
a = np.ones(10)# with all ones
print(a)
a = np.zeros(10,int) # will give all 0 ints
a[0] = "1" # conert element at to 0 to integer 1
a

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
float64
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# 2d arrays
a = np.zeros((2,3)) # array of size 2*3
print(a)
a = np.zeros((2,3,2))#3d array
print(a)
print(a.shape) # gives size of array

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]
(2, 3, 2)


In [16]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c[0] # gives the 0th row
c[:,0]#0th column and all rows

array([1, 4, 7])

In [17]:
 np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [23]:
# Numpy operations
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + 2)# adds 2 to every elemtn of a in contrast to python list where it would have appended 2 to a
print(a+b) # element wise additon, only possible when we have same dimension in both arrays
print(a*2)
print(a*b)
print(a**2)
print(a**b)

[3 4 5]
[5 7 9]
[2 4 6]
[ 4 10 18]
[1 4 9]
[  1  32 729]


In [24]:
print(a.mean())
print(a.sum())

2.0
6


In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6])
d = ((a-b)**2).sum() # gives us distance formula for dist between 2 points
print(d)

27


In [28]:
 a = np.array([5, 1, 2, 1])
 a.mean()

2.25

In [29]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 3, 4, 5])
a.dot(b)

26

In [30]:
a = np.matrix('1 2 4; 3 4 5')
a.shape

(2, 3)

In [31]:
 np.sum([[0, 1], [0, 5]], axis=1)

array([1, 5])